### PR TITLE
docs(Index): Improve schema discovery by adding groupings and roles

### LINKED ISSUE #152: Docs: improve index.html
We finally :blush: have an index page https://schema.stenci.la/. However, it could do with some improvements. I suggest that we keep the current page as `/alphabetic.html` with the following minor tweaks:

- give it a title
- make it an unordered list
- add tags for role, status, category

Then create a new page `/categories.html` that groups the schemas by the `category` property with tags for `role` and `status`

Then convert add links to those, and the files in `docs` into the  `README.md` and convert it to `index.html`.

### PR DESCRIPTION
**Pull request by alex-ketch**
Closes #152 

This PR adds groupings and status indicators to the schema listings.
Two deviations from the issue:
- I didn't add a dedicated _Categories_ page as I thought the sub-list structure on the home page communicated most of the intentions.
- I tried adding the `role` indicators alongside the listings,  but chose not to include them as I thought it was more confusing than helpful given the lack of surrounding context.

Feedback request: Currently the groups don't have an order. Is there a preferred natural order for them? 

Let me know if you think either of the points above are important, and I can add them @nokome 

👁‍🗨 Preview here: https://deploy-preview-163--stencila-schema.netlify.com

### CODE REVIEW

**Comment by nokome** [comment]
1. I don't think a separate categories page is necessary - this is better
2. It's fine excluding `role`
>  Feedback request: Currently the groups don't have an order. Is there a preferred natural order for them?

Prose, Code, Data, Validation, Metadata, Misc ?

**Comment by alex-ketch** [comment]
@nokome I've updated the sorting/rendering. Let me know what you think :)
https://deploy-preview-163--stencila-schema.netlify.com/#available-types

**Comment by nokome** [comment]
:+1: Looks good. The _U_ is rendering funny but that could be a just a four-year-old-outdated-ubuntu-install issue :man_shrugging: 

image

Maybe change text to "are considered unstable and have a higher likelihood of changes".

**Comment by alex-ketch** [comment]
😢 to the test tube emoji
Screen Shot 2020-01-22 at 15 34 04

👍 to "are considered unstable and have a higher likelihood of changes"

**Pull request merged**
