### PR TITLE
adding start of work for dockerized development environment

### PR DESCRIPTION
**Pull request by vsoch**
@nokome here is the start of work to create a Dockerized development environment! The user should be able to build this container, shell in (with working files mounted with volume) and then run `make docs`, etc. I'm not sure about the R/python/npm dependencies so this is as far as I got. Please push to /update this branch to make it work! This will make it easier to test and add the additional documentation files for #214  

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by nokome** [comment]
I made some progress on this and it seems to work for doing `npm run build` and `npm run docs` (although there is an error unrelated to being in a Docker container) at least. I'd like to finish the R install tomorrow and check the Python dev environ works.

**Comment by vsoch** [comment]
Great! I just ran into this issue with `make docs`
```
# make docs
sh: 1: markdown-toc: not found

# npm run build
sh: 1: ts-node: not found
```
Likely we should have all dependencies ready to go - let me know when I can test again! And there is definitely no rush here, I'm having fun and look forward to the next round of work.

**Comment by vsoch** [comment]
@nokome I had added the Rprofile because it spit out an error about not specifying a mirror when I tried to install R packages. If you found a way to not need that, fantastic!

**Comment by nokome** [comment]
Yes, I thought that must have been the case. Seems to be unnecessary with the current setup.

**Comment by nokome** [comment]
@vsoch I have merged this now, along with some other tweaks to the build.

The errors you got with `make docs` are weird because `markdown-toc` and `ts-node` as dependencies listed in the `package.json`. Can you please test again and create new issues / PR if it still does not work.

**Comment by vsoch** [comment]
I'll add comments to the other PR. Thank you!

**Pull request merged**
