### PR TITLE
feat: Add subjects schema

### PR DESCRIPTION
**Pull request by asisiuc**
This is a PR related to adding subjects to the schema: #209

### CODE REVIEW

**Comment by nokome** [comment]
Thanks for getting started on this @asisiuc. It is quite a long standing issue that would be good to resolve.

First, to help discussion, some examples of the data in JATS that we are attempting to represent in this schema. From https://github.com/stencila/encoda/issues/468 and https://jats.nlm.nih.gov/archiving/tag-library/1.1/element/subj-group.html

```xml
<article-categories>
    <subj-group subj-group-type="display-channel">
        <subject>Tools and Resources</subject>
    </subj-group>
    <subj-group subj-group-type="heading">
        <subject>Neuroscience</subject>
    </subj-group>
    <subj-group subj-group-type="heading">
        <subject>Structural Biology and Molecular Biophysics</subject>
    </subj-group>
</article-categories>
```

```xml
<article-categories>
  <subj-group subj-group-type="keywords"> 
    <subject>Biological Sciences</subject>
    <subj-group subj-group-type="keywords">
      <subject>Neuroscience</subject>
      <subj-group subj-group-type="keywords">
        <subject>Cellular and Molecular Biology</subject>  
        <subj-group subj-group-type="keywords">
          <subject>Blood brain barrier</subject>
        </subj-group>
      </subj-group>
    </subj-group>
  </subj-group> 
</article-categories>
```

We have tried to use existing schema.org properties and types as much as possible and avoid creating custom properties and types unless it is really necessary. I'd like to look at the potential to use existing properties on https://schema.org/Article before adding both a new property and a new type, as you are proposing here.

There are several schema.org properties which jump out as ones we could use:

- `about`: The subject matter of the content. Inverse property: `subjectOf` (can be an array of `Things`)
- `genre`: Genre of the creative work, broadcast channel or group (can be an array of `Text` or `URL`)
- `keywords`:  Keywords or tags used to describe this content. (can be an array of `Text`)

My reading of JATS `<subj-group>` and `<subject>` element is that they encompass information across all of these properties. I propose that we use logic which places the data from `<subject>` on different properties based on the value of the `subj-group-type` property:

- if `subj-group-type` is in `['keywords', 'kwd']` then add the text of `<subject>` to the array of `Article.keywords`
- if `subj-group-type` is in `['display-channel', ‘heading’, ‘Toc-heading’, ‘toc’, ‘banner’]`  (see https://jats4r.org/subjects-and-keywords section 9.2) then add the text of `<subject>` to the array of `Article.genres`
- if `subj-group-type` is in `[‘subject’, ‘discipline’, ‘section’, ‘primary/secondary’, ‘system taxonomy’, ‘taxonomy’]` (see https://jats4r.org/subjects-and-keywords section 9.3) then add text of `<subject>` to the `Article.about` array as:
   - the `name` of a [`DefinedTerm`](https://schema.org/DefinedTerm), or
  - if appropriate, the `name` of a more specialised `Thing`, for example a [`Taxon`](https://bioschemas.org/profiles/Taxon/0.6-RELEASE/)

If we take that approach, then we could replace your `Subject` type with a new `DefinedTerm` e.g.

```yaml
title: DefinedTerm
'@id': schema:DefinedTerm
status: stable
role: secondary
category: metadata
description: A word, name, acronym, phrase, etc. with a formal definition.
$comment: |
  Often used in the context of category or subject classification,  glossaries or dictionaries, product or creative work types, etc. 
  Use the `name` property for the term being defined, use `termCode`. If the term has an alpha-numeric code allocated, use
  description to provide the definition of the term.
properties:
  termCode:
    '@id': schema:termCode
    description: A code that identifies this DefinedTerm within a DefinedTermSet
    type: string
required:
  - name
```

and then on `CreativeWork`, instead of adding `subjects`, add `about` and `genre` properties:

```yaml
  about:
    '@id': schema:about
    description: The subject matter of the content.
    type: array
    items:
      $ref: Thing
  genre:
    '@id': schema:genre
    description: Genre of the creative work, broadcast channel or group.
    type: array
    items:
      type: string
```

Once we have decided on the best approach and implement decoding from JATS, to close the following issues, we need to encode this information to HTML:
- https://github.com/elifesciences/issues/issues/5476
- https://github.com/elifesciences/issues/issues/5472

cc @FAtherden-eLife @emmyft

**Comment by FAtherden-eLife** [comment]
> if subj-group-type is in ['keywords', 'kwd'] then add the text of <subject> to the array of Article.keywords

I think it would be fine to treat these in the same way you suggest treating `[‘subject’, ‘discipline’, ‘section’, ‘primary/secondary’, ‘system taxonomy’, ‘taxonomy’]`, as keywords should really be captured in `<kwd-group>` - https://jats.nlm.nih.gov/archiving/tag-library/1.2/element/kwd-group.html (and those could be decoded as `keywords`). 

Even in that case you cite above:
```xml
<article-categories>
  <subj-group subj-group-type="keywords"> 
    <subject>Biological Sciences</subject>
    <subj-group subj-group-type="keywords">
      <subject>Neuroscience</subject>
      <subj-group subj-group-type="keywords">
        <subject>Cellular and Molecular Biology</subject>  
        <subj-group subj-group-type="keywords">
          <subject>Blood brain barrier</subject>
        </subj-group>
      </subj-group>
    </subj-group>
  </subj-group> 
</article-categories>
```

this is essentially a taxonomy of subjects related to an article, so `about` might be more appropriate.

**Comment by asisiuc** [comment]
Thanks for your reply @nokome @FAtherden-eLife, we updated PR following your advice. The build has failed thought and we can't test on our Windows machines so if you can please take a look and confirm this is right.

**Comment by nokome** [comment]
Thank you @asisiuc . I will merge this and make any fixes on master.

**Pull request merged**
