### PR TITLE
[WIP] Review and refine text nodes 🐶

### PR DESCRIPTION
**Pull request by nokome**
This PR reviews and refines textual node types (i.e. those in the `text` folder). It aims to stabilise these types as a target for conversion to/from formats such as Markdown, JATS HTML in the `convert` repo. There is a sister PR over there which uses this branch.

A current list of nodes is below (based mostly on `mdast`) but we need to check that we support important node types in other formats (in particular JATS and HTML).

Block nodes:
  - [x] `Blockquote`
  - [x] `Heading`
  - [x] `List`, `ListItem`
  - [x] `Paragraph`
  - [x] `Table`, `TableRow`, `TableCell`
  - [x] `ThematicBreak`
  - Others? (e.g. `Figure`)

Inline nodes:
  - [x] `Emphasis`
  - [x] `Strong`
  - [x] `Delete`
  - [x] `Verbatim`
  - Others? (e.g. `ImageDisplay`)

### CODE REVIEW

**Comment by beneboy** [comment]
How far are we going down the HTML route? `Span` seems one that's missing.

Do nodes also get `class`, `style`, `id` attributes?

**Comment by nokome** [comment]
@beneboy : sorry only just saw this for some reason.

> How far are we going down the HTML route? Span seems one that's missing.
> Do nodes also get class, style, id attributes?

I'm pretty sure that we want to keep the schema as "sematically pure" as possible and avoid node types and properties that are "presentational". Admittedly, here is sometimes are blurred line between what is presentation and what is data.

All nodes will have a `id` (optional) property but not `class` and `style`.

You may be interested in the related work on the HTML "compiler": https://github.com/stencila/convert/blob/stabilize-text/src/html.ts

**Comment by nokome** [comment]
There are three main changes so far:

- Add a `content` property to `CreativeWork` and remove `articleBody` from `Article`. This was after some discussion with @alex-ketch - we agreed that `content` was more consistent with use elsewhere and complements `CreativeWork.text` for unstructured content.

- Remove `ListItem`: this didn't seem necessary at this stage. Now the `items` of a `List` can be any node:

```yaml
  items:
    '@id': 'schema:itemListElement'
    description: The items in the list
    type: array
    items:
      $ref: Node.schema.yaml
```
- Previously, `Table` allowed for sparse `cells` located in the table using `Cell.position`. However, this structure is different from most other schemas e.g. `MDAST`, `HTML` `gdoc` - which use a row based layout for tables. So I propose using purely row based layout for `Table` (just like a HTML table) and column based layout for `Datatable` (which creates a nice symmetry :). We can reintroduce optimisation for sparse tables later.

The types checked above are ones which don't seem to need much review. The other's will need some decision making around them (I think).

**Comment by nokome** [comment]
@alex-ketch: I'd like to merge this so that we can get a a new npm release that we can use in https://github.com/stencila/convert/pull/42. I think it's OK to go as it is but it would also be great to check/add documentation for the nodes involved in this PR. Either way, please go ahead and merge when you are ready.

**Pull request merged**
